[wintomcat]
172.16.20.54
172.16.20.61

[wintomcat:vars]
#ansible_user=ljanev.agco@moa.gov.ge
ansible_user=ansible
ansible_password=ZokiBilder798$
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
#ansible_winrm_kerberos_delegation=true
db_driver_name=org.postgresql.Driver
db_connstring=jdbc:postgresql://172.16.20.57:5432/postgres
db_username=postgres
db_password=postgis
db_type=POSTGRES
db_schema=naits
